/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as customerRouteRouteImport } from './routes/(customer)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as customerIndexRouteImport } from './routes/(customer)/index'
import { Route as AdminDiscountsRouteImport } from './routes/admin/discounts'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as customerWishlistRouteImport } from './routes/(customer)/wishlist'
import { Route as customerPaymentCallbackRouteImport } from './routes/(customer)/payment-callback'
import { Route as customerOrdersRouteImport } from './routes/(customer)/orders'
import { Route as customerCheckoutRouteImport } from './routes/(customer)/checkout'
import { Route as customerCartRouteImport } from './routes/(customer)/cart'
import { Route as customerAboutRouteImport } from './routes/(customer)/about'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as customerStoreIndexRouteImport } from './routes/(customer)/store/index'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminOrdersIdRouteImport } from './routes/admin/orders/$id'
import { Route as customerStoreIdRouteImport } from './routes/(customer)/store/$id'
import { ServerRoute as ApiUploadthingServerRouteImport } from './routes/api/uploadthing'
import { ServerRoute as ApiPaymentsWebhookServerRouteImport } from './routes/api/payments/webhook'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const customerRouteRoute = customerRouteRouteImport.update({
  id: '/(customer)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const customerIndexRoute = customerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => customerRouteRoute,
} as any)
const AdminDiscountsRoute = AdminDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const customerWishlistRoute = customerWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => customerRouteRoute,
} as any)
const customerPaymentCallbackRoute = customerPaymentCallbackRouteImport.update({
  id: '/payment-callback',
  path: '/payment-callback',
  getParentRoute: () => customerRouteRoute,
} as any)
const customerOrdersRoute = customerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => customerRouteRoute,
} as any)
const customerCheckoutRoute = customerCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => customerRouteRoute,
} as any)
const customerCartRoute = customerCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => customerRouteRoute,
} as any)
const customerAboutRoute = customerAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => customerRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const customerStoreIndexRoute = customerStoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => customerRouteRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const customerStoreIdRoute = customerStoreIdRouteImport.update({
  id: '/store/$id',
  path: '/store/$id',
  getParentRoute: () => customerRouteRoute,
} as any)
const ApiUploadthingServerRoute = ApiUploadthingServerRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiPaymentsWebhookServerRoute =
  ApiPaymentsWebhookServerRouteImport.update({
    id: '/api/payments/webhook',
    path: '/api/payments/webhook',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof customerIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/about': typeof customerAboutRoute
  '/cart': typeof customerCartRoute
  '/checkout': typeof customerCheckoutRoute
  '/orders': typeof customerOrdersRoute
  '/payment-callback': typeof customerPaymentCallbackRoute
  '/wishlist': typeof customerWishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/store/$id': typeof customerStoreIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/store': typeof customerStoreIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof customerIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/about': typeof customerAboutRoute
  '/cart': typeof customerCartRoute
  '/checkout': typeof customerCheckoutRoute
  '/orders': typeof customerOrdersRoute
  '/payment-callback': typeof customerPaymentCallbackRoute
  '/wishlist': typeof customerWishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/store/$id': typeof customerStoreIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/store': typeof customerStoreIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(customer)': typeof customerRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(customer)/about': typeof customerAboutRoute
  '/(customer)/cart': typeof customerCartRoute
  '/(customer)/checkout': typeof customerCheckoutRoute
  '/(customer)/orders': typeof customerOrdersRoute
  '/(customer)/payment-callback': typeof customerPaymentCallbackRoute
  '/(customer)/wishlist': typeof customerWishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/(customer)/': typeof customerIndexRoute
  '/(customer)/store/$id': typeof customerStoreIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/(customer)/store/': typeof customerStoreIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/payment-callback'
    | '/wishlist'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/discounts'
    | '/store/$id'
    | '/admin/orders/$id'
    | '/admin/products/new'
    | '/store'
    | '/admin/orders'
    | '/admin/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/orders'
    | '/payment-callback'
    | '/wishlist'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/discounts'
    | '/store/$id'
    | '/admin/orders/$id'
    | '/admin/products/new'
    | '/store'
    | '/admin/orders'
    | '/admin/products'
  id:
    | '__root__'
    | '/(auth)'
    | '/(customer)'
    | '/admin'
    | '/(auth)/forgot-password'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(customer)/about'
    | '/(customer)/cart'
    | '/(customer)/checkout'
    | '/(customer)/orders'
    | '/(customer)/payment-callback'
    | '/(customer)/wishlist'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/discounts'
    | '/(customer)/'
    | '/(customer)/store/$id'
    | '/admin/orders/$id'
    | '/admin/products/new'
    | '/(customer)/store/'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  customerRouteRoute: typeof customerRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/uploadthing': typeof ApiUploadthingServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookServerRoute
}
export interface FileServerRoutesByTo {
  '/api/uploadthing': typeof ApiUploadthingServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/uploadthing': typeof ApiUploadthingServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/uploadthing' | '/api/auth/$' | '/api/payments/webhook'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/uploadthing' | '/api/auth/$' | '/api/payments/webhook'
  id: '__root__' | '/api/uploadthing' | '/api/auth/$' | '/api/payments/webhook'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiUploadthingServerRoute: typeof ApiUploadthingServerRoute
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiPaymentsWebhookServerRoute: typeof ApiPaymentsWebhookServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)': {
      id: '/(customer)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof customerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(customer)/': {
      id: '/(customer)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof customerIndexRouteImport
      parentRoute: typeof customerRouteRoute
    }
    '/admin/discounts': {
      id: '/admin/discounts'
      path: '/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AdminDiscountsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(customer)/wishlist': {
      id: '/(customer)/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof customerWishlistRouteImport
      parentRoute: typeof customerRouteRoute
    }
    '/(customer)/payment-callback': {
      id: '/(customer)/payment-callback'
      path: '/payment-callback'
      fullPath: '/payment-callback'
      preLoaderRoute: typeof customerPaymentCallbackRouteImport
      parentRoute: typeof customerRouteRoute
    }
    '/(customer)/orders': {
      id: '/(customer)/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof customerOrdersRouteImport
      parentRoute: typeof customerRouteRoute
    }
    '/(customer)/checkout': {
      id: '/(customer)/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof customerCheckoutRouteImport
      parentRoute: typeof customerRouteRoute
    }
    '/(customer)/cart': {
      id: '/(customer)/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof customerCartRouteImport
      parentRoute: typeof customerRouteRoute
    }
    '/(customer)/about': {
      id: '/(customer)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof customerAboutRouteImport
      parentRoute: typeof customerRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(customer)/store/': {
      id: '/(customer)/store/'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof customerStoreIndexRouteImport
      parentRoute: typeof customerRouteRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(customer)/store/$id': {
      id: '/(customer)/store/$id'
      path: '/store/$id'
      fullPath: '/store/$id'
      preLoaderRoute: typeof customerStoreIdRouteImport
      parentRoute: typeof customerRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/payments/webhook': {
      id: '/api/payments/webhook'
      path: '/api/payments/webhook'
      fullPath: '/api/payments/webhook'
      preLoaderRoute: typeof ApiPaymentsWebhookServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface customerRouteRouteChildren {
  customerAboutRoute: typeof customerAboutRoute
  customerCartRoute: typeof customerCartRoute
  customerCheckoutRoute: typeof customerCheckoutRoute
  customerOrdersRoute: typeof customerOrdersRoute
  customerPaymentCallbackRoute: typeof customerPaymentCallbackRoute
  customerWishlistRoute: typeof customerWishlistRoute
  customerIndexRoute: typeof customerIndexRoute
  customerStoreIdRoute: typeof customerStoreIdRoute
  customerStoreIndexRoute: typeof customerStoreIndexRoute
}

const customerRouteRouteChildren: customerRouteRouteChildren = {
  customerAboutRoute: customerAboutRoute,
  customerCartRoute: customerCartRoute,
  customerCheckoutRoute: customerCheckoutRoute,
  customerOrdersRoute: customerOrdersRoute,
  customerPaymentCallbackRoute: customerPaymentCallbackRoute,
  customerWishlistRoute: customerWishlistRoute,
  customerIndexRoute: customerIndexRoute,
  customerStoreIdRoute: customerStoreIdRoute,
  customerStoreIndexRoute: customerStoreIndexRoute,
}

const customerRouteRouteWithChildren = customerRouteRoute._addFileChildren(
  customerRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDiscountsRoute: typeof AdminDiscountsRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDiscountsRoute: AdminDiscountsRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  customerRouteRoute: customerRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiUploadthingServerRoute: ApiUploadthingServerRoute,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiPaymentsWebhookServerRoute: ApiPaymentsWebhookServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
